/******************************************************************************
 * File:        Dio_Cfg.h
 * Module:      Dio (Digital I/O Driver) - Configuration-Generated Symbols
 * Standard:    AUTOSAR Classic Platform R24-11
 * SWS Ref:     AUTOSAR_CP_SWS_DIODriver, section 10.1 (configuration containers)
 * Notice:      DEMO CONFIG - Channel symbol mapping. In production this is
 *              generated by the Dio configuration tool from ARXML
 *              (DioPort / DioChannel containers, SWS 10.1.4 / 10.1.5).
 * Source:      CAR-007 section 4 (symbolic-to-physical mapping).
 *****************************************************************************/

#ifndef DIO_CFG_H
#define DIO_CFG_H

/* Inherit Dio_ChannelType (uint16) from the base Dio header, per CAR-007 sec.4
 * and Dio.h line 58. Channel ID layout: PortId = ChannelId / 16,
 * PinId = ChannelId % 16. */
#include "Dio.h"

/*============================================================================*/
/* CONFIGURATION-GENERATED CHANNEL SYMBOLS (CAR-007 section 4)                 */
/*============================================================================*/

/* LedOut actuator: port 1, pin 2 -> ChannelId 0x12 (decimal 18) */
#define DIO_CHANNEL_LED1   ((Dio_ChannelType)0x12u)

/* Switch sensor: port 0, pin 5 -> ChannelId 0x05 (decimal 5) */
#define DIO_CHANNEL_SW1    ((Dio_ChannelType)0x05u)

#endif /* DIO_CFG_H */
